[package]
name = "buildrs-linking-bug"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "other-bin"
path = "src/other-bin.rs"

[dependencies]
fork = "0.2.0"

[build-dependencies]
bindgen = "0.69.4"

[env]
OUT_DIR = "./out-dir"
